config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  
  get 'home/about'
  root 'pins#index'
  get 'home/homework'
  get 'home/website_info' 
  
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles =>{ :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type =>/\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end  
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def homework
  end
  
  def website_info
  end   
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end
    
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data
    -toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Harvest Expert', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li><%=link_to 'Home', root_path %></li>
      <li><%=link_to 'About Me', home_about_path %></li>
      <li><%=link_to 'Typos!', home_homework_path %></li>
      <li><%=link_to 'Website Info', home_website_info_path %></li>
      <% if user_signed_in?%>
        <li><%=link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%=link_to 'Add Pin', new_pin_path %></li>
        <li><%=link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>  
        <li><%=link_to 'Login', new_user_session_path %></li>
        <li><%=link_to 'Join', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<body>

<h3><u>A Quick Introduction</u></h3>

<p>In order to express my interest in working at Harvest, I've adapted this website to provide an elongated and somewhat informal look at my professional career to date. 
I sort of indirectly developed this website for you, so I hope you like it! It was my first exposure to Ruby, and 
I wrote the vast majority of the code while I was on vacation, so it turned out to be a really fun way to pass the time traveling. 
Please visit the <u><a href="http://harvestexpert.herokuapp.com/home/website_info">Website Info</a></u> page for more detailed information about this website.
</p>
<p>Just for the sake of brevity I'm going to break this out into 3 key areas that will hopefully, when taken in the aggregate, will paint a pretty good picture of who I am as an employee. These sections are as follows:</p>
<p><ul>
 <b><li>History with Customer Service</li>
  <li>Tech Stuff</li>
  <li>Why Harvest?</li></b>
</ul></p>
<p>So now that we have the formalities behind us, lets get into the good stuff!</p>


<h3><u>My History of Providing Customer Service</u></h3>

<p> It’s pretty clear that if you're going to be good at anything and be an effective 'Harvest Expert',
it better be providing great customer service. The tone in which your job posting was written
was encouraging because I feel like the strongest part of my game at this point is, without a doubt,
my customer service experience. Being that customer service is seemingly such an integral part of this position,
I'm going to gracefully segue here and focus on how I have, and continue to, deliver thoughtful customer service. </p>

<p>I studied Political Science at the University of Missouri from 2000-2005. Beginning with the Presidential Election of 2004, I started doing side work for a political consulting company here in St. Louis, and got immediately plugged into their grassroots operations. 
Organizing phone banks and door knocking isn't rocket science, but it did require energy and positivity on a daily basis, as well as a commitment to making sure 
your work consistantly beat expectations.  My expierence grew over the course of 4 years culminating in being assigned as the Executive Assistant to Senate Pro-Tem Michael Gibbons 
on his run for Attorney General in 2008. At the time he was arguably one of the most influential Senators in the state of Missouri as well as one of our most important clients. My bosses trusted me to 
spend 10hrs a day with the Senator because they knew I would represent myself and most importantly the company in the best light possible. Having that exposure at that point of my
career was fantastic, the Senator taught me a lot about how to be a professional, and about the importance of taking your time to communicate complex issues on a level everyone can understand.</p>


<p>Shortly after the 2008 election cycle concluded, I got an offer to go to work for Vail Resorts in Colorado, as an Employee Relations Specialist. 
Working in the mountains and skiing on my lunch break had always been a dream of mine, so I took the opportunity without giving it much of a second thought.
My job with Vail Resorts was centered on providing customer service not only to the paying public, but also to the internal employees at Keystone that ran the resort. 
I served as a proxy to their corporate HR structure to help onboard and acclimate the influx of employees coming in each ski season. Vail is very invested in creating an 
"Experience of a Lifetime" for not only their paying customers, but also their employees. We were constantly engaging with our employees and affirming that those corporate ideals were being practiced. On top of the day to day customer service experience the job was providing me, I was also lucky enough to be invited to participate in what they 
call "Potentials" which is a management training program designed to expose employees to the Vail corporate structure and larger business concepts. In this program I 
got a really good look at how a Fortune 500 company drives its core customer service principals from the top down and how their standard of "Experience of a Lifetime" 
emanated into everything they tried to do. When my contract ended with Vail, moved back to St. Louis to be closer to family. I took my current job here at the St. Louis City 
Board of Elections upon returning the summer of 2010.</p>

<p>And that brings us to present day, where I serve as the IT Manager at a smallish government office called the St. Louis City Board of Elections. 
Our primary focus is exactly as it sounds, to administer and certify, any and all elections that are held in the City of St. Louis. 
From a management standpoint, I am caretaker of a system that supports 35 full time employees, I serve as liaison to our Board of Commissioners on long term 
technology strategy and planning, and personally troubleshoot 95% of our day to day user difficulties. Perhaps most relevant to our customer service discussion,
I also serve as the primary contact for any public data request, as well as acting as liaison to all of our outside software and infrastructure vendors. 
As you might imagine, being a public entity, we deal with the general public on a fairly regular basis, particularly around highly contested elections. 
It’s also recorded fact that certain people just love being outraged at the government. The lethal combination of politics and bureaucracy can at times make for some very abrasive elected officials or constituents wanting to speak with you. I can 100% say
without equivocation, that working at the Board of Elections has made me more patient and more effective when dealing in customer service situations.
It has made me better at communicating technology concepts in a way that is universally understandable, it has made me more confident, and has taught me how to be prepared for a 
conversation before it even happens. These are all things I think that come naturally to me to some degree, but working here has really allowed me to refine those qualities
in a professional setting over an extended period of time.</p>

<p><b>Summary:</b> If you'd allow me the courtesy of using fussy math that is roughly a decade’s worth of experience in customer service. More than anything,
I think it speaks to the fact I'm a person varying types of employers have put their trust in to deliver a reliable and consistent product commiserate with their image and standards.<p/>   


<h3><u>The Tech Stuff</u></h3>
<p>In 2013 I came to the realization that if I was going to stay in the tech industry I needed to start adding some specialized skill sets to my resume. Being that I studied Political Science at Mizzou, 
I had no classic schooling or training in the tech field, so I enrolled in a program through UCLA in Systems Analysis. 
It gave me an in depth look at everything from Agile software development, to actual coding best practices and techniques. 
I completed that program in just under 15 months. Just recently I also enrolled in a Software Development program at Cal-Berkeley, I am currently completing courses in Javascript and Python.  

Below are some of the launguages and technologies I worked with through these programs, and others I have picked up myself along the way. I’m really looking for a position that will allow me to lean on my 
generalist expierence yet still allow me to poke through someone else's code, and maybe hack out a little bit of my own.

</p>
<pre>
<b>Familiar Languages:</b>    -- SQL       -- C              -- HTML      -- CSS               --jQuery         
                       -- RUBY      -- Javascript     -- Python    -- Visual Basic      --Git                                      

<b>Software:</b>
Netbeans IDE 8.0, SQL Server Management Studio, Bloodshed Dev C++, Microsoft Visual Studio, Cloud9 Dev Enviroment, Wireshark, Amazon Web Services,
Cisco Meraki MDM, Microsoft Server 2008 R2, Cisco Mobile Device Management 
</pre>

<h3><u>Why Harvest?</u></h3>
<p>I found Harvest through a random job board a couple of years ago, and I have been idly keeping an eye on your career section since that time. I've wanted to apply to this opening previously, 
but the timing has never been quite right. Things have changed significantly for me over the last year and a half, and quite honestly, all of a sudden the timing couldn't be anymore perfect. 
On the surface Harvest checks a lot of boxes for me right off the bat. First it’s a small, close knit company that seems like it really invests in its culture as a means to ensure quality.
Secondly, you use an Agile framework and have also been known to utilize pair programming, two things I was really hoping for in my next position. 
And my third point will take just a minute to explain, so please allow me to indulge myself:</p>

<p>In your <b>“Secret Tips for Applying to Harvest”</b> you stated that I should know something about Harvest, 
so I spent some time learning the back stories for some of your current employees and reading through your Tech Time blog.  
I found my way to Danny Wen’s Tumblr page, and two postings he had there are what pushed me to 
finally put all this together and apply. </p>

<p>Here is a quote from Danny's Tumblr:</p>
<blockquote>“If you take somebody who has high cognitive ability, 
is innately curious, willing to learn and has emergent leadership skills, 
and you hire them as an H.R. person or finance person, 
and they have no content knowledge, and you compare them with someone who’s been doing just one thing and is a world expert, the expert will go: 
‘I’ve seen this 100 times before; here’s what you do.’ ” Most of the time the nonexpert will come up with the same answer, added Bock, 
“because most of the time it’s not that hard.” Sure, once in a while they will mess it up, he said, 
but once in a while they’ll also come up with an answer that is totally new. And there is huge value in that."</blockquote>
<p>Here is another qoute from an article linked on Danny's Tumblr:</p>
<blockquote>I have 46 Thanksgiving dinners left with my family. After that, I’ll be dead. Time is the most valuable resource I have. Yet, I don’t manage it like one.</blockquote>
<p>I think both of those statements come from such an enlightened place, if that is the mindset and disposition of the person responsible for running Harvest, then I absolutely want to be a part of the team.
This is exactly the sort of energy and enviroment I want to be surrounded by. I know I can contribute, not just in productivity, but from a positivity and cultural standpoint as well. I want to continue to grow 
as an employee and as a person, and I know Harvest has an established framework that can help facilitate that. 
</p>


<h3><u>In Closing</u></h3>
<p>I think I’m pushing well over 2000 words at this point, so assuming you’re still reading, I’m going to keep this closing brief.
I know for a fact that I would make a great Harvest Expert, I have the experience, the desire, and the temperament to deliver excellent customer service to Harvest’s clients. 
Beyond that, I’m a thoughtful human being and a gracious teammate, but most importantly I have a history of being a really good employee. </p>

</body>
</html>

app/views/home/homework.html.erb
<h3><u>Typos!</u></h3>
<p>I don't need to tell you this, but your job posting had a fair number of grammatical mistakes. The following are the corrections 
I would make to that particular copy.</p>

<h4>Intro</h4>
<p><ul>
 <li>Harvest Experts: wicked-smart human beings, empathetic problem-solvers, and patient trouble-shooters. <font color="red">("beings" not "being") </font></li></b>
</ul></p>


<h4> About You</h4>
<p><ul>
  <li>You can gracefully break down, solve, and explain even the most complex problems. <font color="red">(removed comma after explain)</font></li>
  <li>You’re self-motivated, but also enjoy contributing to a team. <font color="red">(inserted hyphen)</font></li>
  <li>You’re thorough—no detail goes unnoticed. <font color="red">("goes" not "go")</font> </li>
  <li>You don’t mind doing the same thing from day-to-day. <font color="red">(inserted hyphen)</font> </li>
  <li>...onto a side project when the occasion arises, and aren’t scared to tackle the new and unknown. <font color="red">(inserted comma after arises)</font> </li>
</ul></p>

<h4>What You'll Do</h4>
<p><ul>
 <li>...Harvest Forecast, and our associated apps and integrations. <font color="red">("our" not "are") </font></li>
  <li>...video documentation for Harvest's Help Center, and keep this documentation up-to-date. <font color="red">(inserted apostrophe in Harvests)</font></li>
  <li>Troubleshoot technical issues in Harvest, and help developers diagnose bugs. <font color="red">(inserted comma after Harvest)</font> </li>
</ul></p>

<h4>To Apply</h4>
<p><ul>
 <li>Tell us a bit about yourself, and why you’d make a great Harvest Expert. <font color="red">(inserted comma after yourself and removed "you") </font></li>
</ul></p>

app/views/home/index.html.erb
<div class="jumbotron">
 <h1>Welcome to My APP</h1>
 <p>Its gonna be super cool</p>
 <%=link_to 'About Us',home_about_path, class:'btn btn-default'%>
 <%=link_to 'Home',root_path, class:'btn btn-primary'%> 
</div>

app/views/home/website_info.html.erb
<h3><u>Whats Going on Here?!?!?</u></h3>
<p>I wanted to use this space to talk a little bit about this website you're using. The bulk of this code was written on a 10 
day vacation I took to Florida and South Carolina. I knew I was going to be spending alot of time in and out of airports, and just traveling 
in general, so I thought it would be nice to have a project to work on during that time. I had already been somewhat mentally preparing myself to apply to this position, 
so I opted to pick up a book on Ruby on Rails thinking it might give me some additional persepctive I might be able to use
when applying. I picked up  <u><a href="http://www.amazon.com/Learn-Ruby-Rails-For-Development/dp/0692364218" target="_blank"> Learn Ruby on Rails for Web Development</a></u> 
by John Elder from Amazon and this site is the 
intended result of that particuar text. I think the easiest thing to do is just to lay out the main componets and highlight some of the concepts that were used to put
this together:

<p><ul>
 <b><li>Cloud9, GitHub, and Heroku</li>
  <li>Bootstrap </li>
  <li>Devise </li>
  <li>Scaffolding (CRUD!)</li>
  <li>User Authentication</li>
  <li>Table Creation and Database Associations</li>
  <li>Postgres and SQLite3 </li>
  <li>Paperclip and ImageMagick</li>
  <li>Amazon Web Services </li>
  <li>JQuery Masonry</li></b>
</ul></p>
 </p>
 <p> This site was built as a clone of Pinterest, thats why on the landing page you're seeing a handful of my old vacation photos (Hiking Zion Canyon in Utah for those interested). 
 As it was explained in the text, building a Pinterest clone was the chosen excerise because it provided exposure to a broad range 
 of topics, and it plainly illustrated a fundamental building block of creating any type of web app, CRUD (Create, Read,
 Update, Destroy). At its core I have built an app that will allow someone to create users, log in and out of the app,
 upload text and images to a database, and edit or delete uploaded content as needed. In compairison to some
 of the other languages I've learned, Ruby made implementing those mechinisms pretty straighforward. That being said, by no means
 does completing one web app mean that I am suddenly qaulified to work on your product, but hopefully it shows some initative and at the very least an ability to learn 
 independently. Also if I'm not mistaken I believe you use/have used AWS and Paperclip for some of your image hosting, so there
 is some technology overlap there as well. 
 
 
 
 
 </p>
 
 <h3><u>To-Do List</u></h3>
 <p>This is the first thing I've ever done with Ruby, and I'm sure to the trained eye, it probably shows. 
 When I was building this site, I subscribed to the theory that if I encountered a hiccup, and it didn't 
 directly imapct the funtionality of the site, I made note of it and moved on. I wanted to get a "finished product", test its
 functionality, and then fix the bugs I could reasonably expect to fix being a novice to Ruby. Below I'll highlight a couple of things that
 need improving, or didn't go exactly to plan, in order of importance.</p>
 
 <p><b>Display Issues--Home Page</b></p>
 <p>You'll notice that I currently have it designed so that each page only displays 5 "Pins" per page. I did that specifically to eliminate
 one of the flaws I encountered and couldn't find a sutable answer to. Lets assume it was set to display 20 pins per page, in 4 rows of 5. 
 If a user were to upload a photo that wasn't a standard size, i.e. a long and skinny photo/tall and narrow, when that pin was bumped out of
 the first row, it would cause an issue with the container grid causing the pins not to display correctly. It will cause large offsets seemingly for no reason around the pin, 
 throwing the other pins out of the nice grid pattern they should be displayed in. This seemed to become an issue when I implemented Masonry on top of Bootstrap, which I read online may cause issues. So I'm 
 not sure if there is a conflict between the two in some way, if the containers need to be adjusted to accomodate irregular sizes, or if I'm missing a more obvious answer all together. I tried rolling back my code and reinstalling the
 Masonry set up, but that didn't seem to correct things. My solution to the problem was to limit the number of pins displayed so that a second row was never needed, and that essentially "fixed" the problem.
 Obviously that is a short term solution to a long term problem and one that directly impacts the visual and interactive feel of the website.</p>
 
 <p><b>Mobile Integration</b></p>
 <p>If you were to visit this website on a mobile device, at first glance things would appear to be as expected. Once you try to navigate around the site though, you'll see a major problem. 
 The mobile menu button doesn't work, which makes the site virtually unusable on a mobile device. The menu button on the top right isn't "clickable" for lack of a better term. The book only 
 included about a paragraph and a half on making the site mobile friendly and instucted me to use the Viewport meta tag to do all the work for me. Well needless to say, it wasn't quite that simple. 
 I did see that potientially I need to specify a clickable class for my menu, but any and all attempts at getting a straight answer on the subject were unsuccessful. These are the kind of problems that drive me crazy. 
 I tend to waste massive amounts of time running in circles, when all I need is a quick conversation with someone more expierenced than me and I'm sure it is an easy and straighforward fix. Such are the joys of learning 
 a new language I suppose.</p>
 
 <p><b>Wish List</b></p>
 <p> Outside of those two issues, the actual mechinisms that allow the core functionality of the site seem to be working as needed. Not bad for a first timer huh?! Below are just a couple 
 things I think would impove the site, but would be considered "luxury" items by me, as they would probably impact user expierence more than functionality.</p>
  
 <p><ul>
 <b><li>Better CSS</li>
  <li>When viewing pins, allow pins to be displayed in a shadowbox at full size when clicked.</li>
  <li>When creating a new pin, the attach image container is entirely too elongated.</li>
  <li>Each page needs a simple footer, as is, the ending of each page seems abrupt.......</li>
  </b></p>
 </ul></p>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<%= render 'home/header' %>
<div class="container">
  <% flash.each do |name, msg|%>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin,html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
  
      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    
  <div class ="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div> 
  
  <div class="actions">
    <%= f.submit "Submit", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box">
      <div class ="panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %><br/>
        <br/><strong><%=pin.user.name if pin.user%></strong><br/>
        <div class"panel-body">
          <%= pin.description %><br/>
        </div>
        <%if pin.user == current_user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_pin_path(pin) %><br/>
            <%= link_to 'Destroy', pin, method: :delete, data: {confirm: 'Are you sure?'} %><br/>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <%= @pin.description %><br/>
         <br/><%=@pin.user.name %><br/>
        
        <% if @pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(@pin) %>
        <%end %>
        
        <%= link_to 'Back', pins_path %>
        
      </div>
    </div>
  </div>
</div>